version: '3.1'

services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: "my-verdaccio"
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - "./conf:/verdaccio/conf"
      - "./storage:/verdaccio/storage"

networks:
  node-network:
    driver: bridge

volumes:
  storage: